services:
  mysql:
    image: mysql:8.0
    container_name: myfeed-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: myfeed
    ports:
      - "3307:3306"          # 宿主机3307 → 容器3306，避开本机3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: myfeed-redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: myfeed-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    ports:
      - "5672:5672"          # AMQP，程序连这个
      - "15672:15672"        # 管理界面，浏览器打开 http://localhost:15672

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
